# Generated by Django 5.2.7 on 2026-02-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_qty',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
